# Generated by Django 2.1.3 on 2018-11-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20181120_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food'), ('Entertainment', (('T', 'Theater'), ('M', 'Mall'))), ('VEHP', 'Parking'), ('STY', 'Study'), ('Recreational', (('GYM', 'Gym'), ('POOL', 'Swimming Pool'), ('SQUA', 'Squash Court'), ('BSKT', 'Basketball Court'), ('PARK', 'Parks'))), ('INFO', 'Info')], max_length=4),
        ),
    ]
