# Generated by Django 2.1.2 on 2018-11-22 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps', '0003_auto_20181120_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.TextField()),
                ('longitude', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pin',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pin',
            name='category',
            field=models.CharField(choices=[('INFO', 'Info'), ('FOOD', 'Food'), ('VEHP', 'Parking'), ('STY', 'Study'), ('Entertainment', (('T', 'Theater'), ('M', 'Mall'))), ('Recreational', (('GYM', 'Gym'), ('POOL', 'Swimming Pool'), ('SQUA', 'Squash Court'), ('BSKT', 'Basketball Court'), ('PARK', 'Parks')))], default='INFO', max_length=4),
        ),
        migrations.AlterField(
            model_name='pin',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='pin',
            name='latitude',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pin',
            name='longitude',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pin',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
